#include<p18f452.inc>

	CONFIG WDT=OFF
	CONFIG LVP=OFF
	CONFIG OSC=HS
	CONFIG BOR=OFF
	ORG 00
	MOVLW 0x00
	CLRF TRISB
	CLRF PORTB
	CLRF PORTD
	SETF TRISD

	MOVLW 100
START
	CPFSLT PORTD	;PORT < 100
	GOTO FALSE1
	MOVF PORTD, W	;WREG = PORTD
	ADDLW 50		;WREG += 50
	MOVWF PORTB		;PORTB = WREG
	GOTO START

FALSE1
	CPFSGT PORTD	;PORTD > 100
	GOTO FALSE2
	MOVLW 200		;WREG = 200
	CPFSLT PORTD	;PORT < 200	
	GOTO FALSE2
	CLRF PORTB		;PORTB = clear
	GOTO START

FALSE2
	COMF PORTB,W	;WREG = PORTB'
	MOVWF PORTB		;PORTD = WREG
	GOTO START

END